version: "3.8"

services:
  web:
    build:
      dockerfile: docker/development/Dockerfile
      context: .
    container_name: indie
    ports:
      - "5000:5000"
      - "3000:3000"
    env_file: .env
    volumes:
      - ./client:/app/client
      - ./server:/app/server
