version: "3.8"

services:
  web:
    build:
      dockerfile: docker/development/Dockerfile
      context: .
    container_name: indie
    ports:
      - 5000:5000
      - 3000:3000
    env_file: .env
    volumes:
      - .:/app
    depends_on:
      - db
  db:
    image: mongo:4.2-bionic
    ports:
      - 27017:27017
